version: '3'

services:
  mynginx:
    container_name: mynginx
    restart: always
    image: belousov2501/bestnginx:1.0.0
    ports:
      - 86:80
    volumes:
      - type: bind
        source: ./indexNew.html
        target: /www/index.html

